version: "3"

services:
  web:
    container_name: react_app
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "6000:6000"
    command: >
      sh -c "yarn start"
    env_file:
      - .env
networks:
  shared_network:
    external: true