version: "3.7"

services:

  web:
    container_name: react_app
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    command: >
      sh -c "yarn build && serve -s build"
    env_file:
      - .env

networks:
  shared_network:
    external: true