FROM node:18-alpine AS builder
WORKDIR /frontend
COPY package*.json ./
RUN npm ci
COPY . ./
RUN npm run build

# Nginx stage
FROM nginx:1.21-alpine
COPY --from=builder build /var/www/frontend
COPY nginx/nginx-setup.conf /etc/nginx/conf.d/default.conf