# Generated by Django 4.1.7 on 2023-06-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.IntegerField()),
                ('heart', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('steps', models.IntegerField()),
            ],
        ),
    ]
